FROM node:16 AS frontend
WORKDIR /usr/src/app
COPY frontend/ ./frontend/
RUN cd frontend && npm install && npm run build


FROM node:16 AS backend-api
WORKDIR /root/
COPY --from=frontend /usr/src/app/frontend/build ./frontend/build
COPY backend-api/package*.json ./backend-api/
RUN cd backend-api && npm install
COPY backend-api/. ./backend-api/.

EXPOSE 3000
CMD [ "node", "./backend-api/server.js" ]
