
From node:16 as base
WORKDIR /root/
COPY ./frontend/. ./frontend/.

COPY ./backend-api/. ./backend-api/.

COPY .env /root/.

RUN npm ci --prefix ./backend-api

RUN npm ci --prefix ./frontend
RUN npm run build --prefix ./frontend

EXPOSE 3001
CMD [ "node", "./backend-api/server.js" ]